# Generated by Django 4.2.19 on 2025-03-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_order_number_alter_orderlineitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
