# Generated by Django 4.2.19 on 2025-02-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_is_best_seller_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('honey', 'Honey'), ('bee_products', 'Bee Products')], default='honey', max_length=100),
        ),
    ]
