# Generated by Django 4.2.19 on 2025-02-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, choices=[('450g', '450gr'), ('600g', '600gr')], max_length=100, null=True),
        ),
    ]
