# Generated by Django 4.2.19 on 2025-02-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productsize_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, choices=[('450g', '450gr'), ('600g', '600gr'), ('Standard', 'Standard')], max_length=100, null=True),
        ),
    ]
